---

# Charts release configuration file example
# This file is used to update the version of the helm charts and images in the values.yaml file
# It is used in the helm-charts-release action
# ${release} is replaced with the release version provided in the workflow

charts:
  - name: module1
    chart_file: charts/helm/module1/Chart.yaml
    values_file: charts/helm/module1/values.yaml
    image:
      - ghcr.io/netcracker/module1:${release} # This will replace the image version with the release version
      - ghcr.io/netcracker/module1-service1:${release}-${THIRD_PARTY_VERSION} # This will replace the image version with the release version and append the THIRD_PARTY_VERSION variable
      - ghcr.io/netcracker/module1-service2:#5\.\d+\.\d+ # This will select the latest tag matching the Python re regular expression
      - ghcr.io/netcracker/module1-service2:#latest # This will select the latest SemVer tag
