name: Broadcast files to organization repositories
on:
  workflow_call:
    inputs:
      repo_name:
        description: |
          Target repository name.
          If not provided, the action will be triggered for all repositories in the organization.
        type: string
      replicate-common-workflows:
        description: 'Replicate common workflows'
        required: false
        default: true
        type: boolean
      replicate-common-files:
        description: 'Replicate common files'
        required: false
        default: true
        type: boolean
      replicate-cloud-core-dependabot:
        description: 'Replicate dependabot config file for Cloud-Core repos'
        required: false
        default: true
        type: boolean
    secrets:
      GH_ACCESS_TOKEN:
        required: true
permissions:
  pull-requests: write
  contents: read
env:
  GH_ACCESS_TOKEN: '${{ secrets.GH_ACCESS_TOKEN }}'
jobs:
  replicate_common_files:
    name: Replicating common git files
    if: ${{ inputs.replicate-common-files }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Replicating common files
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          repos_to_ignore: >
            KubeMarine, k8s-conformance, gatekeeper-library,
            cassandra-exporter, pg_hint_plan
          exclude_private: true
          exclude_forked: true
          committer_username: NetcrackerCLPLCI
          bot_branch_name: broadcast-common-files
          patterns_to_include: >
            .gitattributes, .editorconfig
          destination: .
          commit_message: 'chore: update of common files'
  replicate_common_config_files:
    name: Replicating common config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Replicating common config files
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          exclude_private: true
          exclude_forked: true
          committer_username: NetcrackerCLPLCI
          bot_branch_name: broadcast-workflows
          patterns_to_include: >
            config/examples/auto-labeler-config.yaml,
            config/examples/release-drafter-config.yml
          destination: .github/
          repos_to_ignore: >
            KubeMarine, k8s-conformance, gatekeeper-library,
            cassandra-exporter, pg_hint_plan
          commit_message: 'chore: update of common config files'
  replicate_superlinter_configs:
    name: Replicate Super-Linter config files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Replicating file
      uses: derberg/manage-files-in-multiple-repositories@v2
      with:
        github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
        patterns_to_include: '.github/super-linter.env,.github/linters'
        exclude_private: true
        exclude_forked: true
        committer_username: NetcrackerCLPLCI
        bot_branch_name: broadcast-workflows
        commit_message: 'chore: [skip ci] update of superlinter config files'
  replicate_common_workflows:
    if: ${{ inputs.replicate-common-workflows }}
    name: Replicate common workflow
    runs-on: ubuntu-latest
    needs: [replicate_common_config_files, replicate_superlinter_configs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Replicating common workflows
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: >
            workflow-templates/cla.yaml,
            workflow-templates/super-linter.yaml,
            workflow-templates/profanity-filter.yaml,
            workflow-templates/automatic-pr-labeler.yaml,
            workflow-templates/pr-conventional-commits.yaml,
            workflow-templates/pr-lint-title.yaml
          destination: .github/workflows
          repos_to_ignore: >
            KubeMarine, k8s-conformance, gatekeeper-library,
            cassandra-exporter, pg_hint_plan
          exclude_private: true
          exclude_forked: true
          committer_username: NetcrackerCLPLCI
          bot_branch_name: broadcast-workflows
          commit_message: 'chore: update of common workflows'
  replicate_cloud_core_dependabot:
    if: ${{ inputs.replicate-cloud-core-dependabot }}
    name: Replicate dependabot config file for Cloud-Core repos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Replicating file
      uses: derberg/manage-files-in-multiple-repositories@v2
      with:
        github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
        patterns_to_include: 'config/dependabot/cloud-core/dependabot.yml'
        destination: .github/
        exclude_private: true
        exclude_forked: true
        topics_to_include: core
        committer_username: NetcrackerCLPLCI
        bot_branch_name: broadcast-dependabot-configs
        commit_message: 'chore: update cloud-core dependabot config file'
  obsoleted_workflow_cleanup:
    name: Obsoleted workflows cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Obsoleted workflow cleanup
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_remove: 'pr-collect-commit-messages.yaml'
          repos_to_ignore: >
            KubeMarine, k8s-conformance, gatekeeper-library,
            cassandra-exporter, pg_hint_plan
          exclude_private: true
          exclude_forked: true
          committer_username: NetcrackerCLPLCI
          bot_branch_name: broadcast-workflows-cleanup
          commit_message: 'chore: cleanup of obsoleted workflows'
