name: Broadcast files to organization repositories
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
permissions:
  pull-requests: write
  contents: read
jobs:
  replicate_common_workflows:
    runs-on: ubuntu-latest
    env:
      REPOS_TO_IGNORE: >-
        qubership-workflow-hub, qubership-test-pipelines, KubeMarine,
        k8s-conformance, gatekeeper-library, cassandra-exporter, pg_hint_plan
      GH_ACCESS_TOKEN: '${{ secrets.GH_ACCESS_TOKEN }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replicating common workflows
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: >-
            workflow-templates/cla.yaml,
            workflow-templates/super-linter.yml,
            workflow-templates/profanity-filter.yaml,
            workflow-templates/automatic-pr-labeler.yaml,
            workflow-templates/pr-collect-commit-messages.yaml,
            workflow-templates/pr-conventional-commits.yaml,
            workflow-templates/pr-lint-title.yaml,
            workflow-templates/cdxgen.yaml
          patterns_to_ignore: 'CLA/netcracker-logo.png,CLA/netcracker-logo.svg'
          destination: .github/workflows
          repos_to_ignore: '${{ env.REPOS_TO_IGNORE }}'
          exclude_private: true
          exclude_forked: false
          branches: '.*-release,main'
          committer_email: CorePaaSGroup@netcracker.com
          committer_username: NetcrackerCLPLCI
          commit_message: 'ci: update of common workflows'
  replicate_git_common_files:
    name: Replicate git common files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: '.gitattributes,.editorconfig,auto-labeler-config.yaml'
          repos_to_ignore: '${{ env.REPOS_TO_IGNORE }}'
          exclude_private: true
          exclude_forked: false
          committer_email: CorePaaSGroup@netcracker.com
          committer_username: NetcrackerCLPLCI
          commit_message: 'ci: update of gitattributes file'
  replicate_cloud_core_dependabot:
    name: Replicate dependabot config file for Cloud-Core repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: config/dependabot/cloud-core/dependabot.yml
          destination: .github/
          repos_to_ignore: '${{ env.REPOS_TO_IGNORE }}'
          exclude_private: true
          exclude_forked: false
          topics_to_include: core
          committer_email: CorePaaSGroup@netcracker.com
          committer_username: NetcrackerCLPLCI
          commit_message: 'ci: update cloud-core dependabot config file'
  replicate_codestyle_configs:
    name: Replicate codestyle config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: '.github/super-linter.env,.github/linters'
          repos_to_ignore: '${{ env.REPOS_TO_IGNORE }}'
          exclude_private: true
          exclude_forked: false
          committer_email: CorePaaSGroup@netcracker.com
          committer_username: NetcrackerCLPLCI
          commit_message: 'ci: update of codestyle config files'
  replicate_example_configs:
    name: Replicate example config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replicating file
        uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
          patterns_to_include: docs/examples/release-drafter-config.yml
          destination: .github/
          repos_to_ignore: '${{ env.REPOS_TO_IGNORE }}'
          exclude_private: true
          exclude_forked: false
          committer_email: CorePaaSGroup@netcracker.com
          committer_username: NetcrackerCLPLCI
          commit_message: 'ci: update example config files'
