on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

name: Create Workflow-Hub GitHub release

permissions:
  contents: write
  actions: write

jobs:

  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.1
        with:
          tag-name: 'v${{ github.event.inputs.version }}'
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preparation:
    needs: [check-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

      - name: Create Release Branch
        run: |
          git checkout -b "release/v${{ inputs.version }}"
          git push origin "release/v${{ inputs.version }}"
      - name: Update references
        run: |
          # shellcheck disable=2038
          find . -type f -name '*.yaml' -or -name '*.yml' -or -name '*.md' -and -not -name 'github-release.yml' | \
          xargs sed -i 's|uses: netcracker/qubership-workflow-hub/\(.*\)@main|uses: netcracker/qubership-workflow-hub/\1@v${{ inputs.version }}|gi'
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update references to the new version"
          git push origin "release/v${{ inputs.version }}"
          git tag "v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
  create-github-release:
    needs: [release-preparation]
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ inputs.version }}
      publish: false
      config-name: release-drafter-config.yml
