---
# The workflow to deploy snapshot artifact versions to Maven Central
# Fill free to adjust java version and additional mvn command-line parameters
# The workflow will trigger on pushes into branches different from main and release
# Please make sure that the version in the pom.xml file has the SNAPSHOT postfix

name: Maven deploy

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        description: "JDK version (e.g. '21')"
        required: false
        default: "21"
      additional-mvn-args:
        type: string
        description: "Additional mvn cmd-line params (e.g. '-Dskip.tests=true')"
        required: false
        default: ""
    secrets:
      maven-user:
        required: false
      maven-token:
        required: true
      gpg-private-key:
        required: false
      gpg-passphrase:
        required: false
permissions:
  contents: write
jobs:
  mvn-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: "Setup xmlstarlet"
        run: |
          sudo apt install -y xmlstarlet
      - name: "Check that version is SNAPSHOT"
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}
          IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml || echo "")
          if [[ "${IS_SNAPSHOT}" == "" ]]
          then
            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
            echo "❗ Workflow will not deploy any artifacts. Please add '-SNAPSHOT' to the revision." >> $GITHUB_STEP_SUMMARY
            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix."
            echo "❗ Workflow will not deploy any artifacts. Please add '-SNAPSHOT' to the revision."
            echo "IS_SNAPSHOT=false" >> $GITHUB_ENV
          else
            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix" >> $GITHUB_STEP_SUMMARY
            echo "✅ Workflow will deploy SNAPSHOT artifact" >> $GITHUB_STEP_SUMMARY
            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix."
            echo "✅ Workflow will deploy SNAPSHOT artifact"
            echo "IS_SNAPSHOT=true" >> $GITHUB_ENV
          fi
      - name: "Set up JDK"
        if: ${{ env.IS_SNAPSHOT == 'true' }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USER
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Display settings.xml
        if: ${{ env.IS_SNAPSHOT == 'true' }}
        run: cat ~/.m2/settings.xml

      - name: "Maven deploy"
        if: ${{ env.IS_SNAPSHOT == 'true' }}
        run: |
          mvn --batch-mode deploy ${{ inputs.additional-mvn-args }}
        env:
          MAVEN_USER: ${{ secrets.maven-user }}
          MAVEN_PASSWORD: ${{ secrets.maven-token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg-passphrase }}
