# The name of the workflow
name: Profanity filter

on: [workflow_dispatch]
# Trigger on issue or pull requests, that are opened, edited, or reopened
#  issue_comment:
#    types: [created, edited]
#  issues:
#    types: [opened, edited, reopened]
#  pull_request:
#    types: [opened, edited, reopened]

# Required permissions
permissions:
  issues: write
  pull-requests: write

jobs:
  apply-filter:
    runs-on: ubuntu-latest
    steps:
    - name: Scan issue or pull request for profanity
      # Conditionally run the step if the actor isn't a bot
      if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
      uses: IEvangelist/profanity-filter@2.0.7
      id: profanity-filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # See https://bit.ly/potty-mouth-replacement-strategies
        replacement-strategy: middle-asterisk # See Replacement strategy
        custom-profane-words-url: https://github.com/Hesham-Elbadawi/list-of-banned-words/raw/refs/heads/master/ru
