# How to implement the workflow in repository
# Create a .github/workflows/profanityFilter.yaml file in the repository and copy code below
# ###################################################
# name: Profanity filter
# on:
#   issue_comment:
#     types: [created, edited]
#   issues:
#     types: [opened, edited, reopened]
#   pull_request:
#     types: [opened, edited, reopened]
# permissions:
#   issues: write
#   pull-requests: write
# jobs:
#   call-apply-filter:
#     uses: Netcracker/qubership-github-workflows/.github/workflows/profanityFilter.yaml@main
# ###################################################

name: Profanity filter
on: [workflow_call]

# Required permissions
permissions:
  issues: write
  pull-requests: write

jobs:
  apply-filter:
    runs-on: ubuntu-latest
    steps:
    - name: Scan issue or pull request for profanity
      # Conditionally run the step if the actor isn't a bot
      if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
      uses: IEvangelist/profanity-filter@221fd3e2de42e4aa8acc56d0739b1134065a54be #9.0.7
      id: profanity-filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # See https://bit.ly/potty-mouth-replacement-strategies
        replacement-strategy: middle-asterisk # See Replacement strategy
        custom-profane-words-url: https://github.com/Hesham-Elbadawi/list-of-banned-words/raw/refs/heads/master/ru
