name: GitHub Release Drafter

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Release version'
      ref:
        description: "Branch name to create release from"
        required: false
        type: string
        default: main
      publish:
        description: 'Enable publish release?'
        required: false
        default: 'false'
        type: string
      config-name:
        description: 'Release Drafter configuration file'
        required: false
        default: 'release-drafter-config.yml'
        type: string
      tag:
        description: 'The tag name to be associated with the GitHub release'
        required: false
        type: string

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Release version: ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag: ${{ inputs.tag || format('v{0}', inputs.version) }}" >> $GITHUB_STEP_SUMMARY
          echo "Enable publish release: ${{ inputs.publish }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref ||  github.ref_name }}

      - name: Run Release Drafter
        uses: netcracker/release-drafter@master
        with:
          config-name: ${{ inputs.config-name }}
          publish: ${{ inputs.publish }}
          name: ${{ env.RELEASE_VERSION }}
          tag: ${{ inputs.tag || format('v{0}', inputs.version) }}
          version: v${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ inputs.version }}
